#!/usr/bin/env bash

# To be launched from project root

theme=$1

# Node part

cd "$theme/$theme"
npm install --cache ../../.npm-cache --prefer-offline
npm run deploy

# Python part
cd ..
rm -rf dist
python -m build